.TH HTab 1 "2007-01-08" "HTab 1.3" "USER COMMANDS"
.SH NAME
HTab \- terminating tableaux system for hybrid logic
.SH SYNOPSIS
.B htab
[OPTIONS]
.SH DESCRIPTION
HTab is a theorem prover and model builder for
the hybrid logic equipped with the universal
modality, guaranteeing termination for all
formulas of this language.
.SH OPTIONS
.TP
\-h, \-?, \--help
display help
.TP
\-f FILE, \--input-file=FILE
obtain input formulas from FILE instead of STDIN
.TP
\-q, \--quiet, \--silent
suppress all normal output
.TP
\-s, \--log-state
display the internals of the tableaux and the rules used during the calculus
.TP
\-l FILE, \--latex-output=FILE
create a LaTeX file of the internals of the tableaux and the rules used during the calculus
.TP
\-b [0|1], \--semantic-branching=[0|1]
disable/enable semantic branching (default is enabled)
.TP
\-c [0|1], \--full-clash=[0|1]
disable/enable full clash (default is enabled)
.TP
\-t T, \--timeout=T
run for at most T seconds. Default is no limit.
.TP
\-m FILE, \--save-model=FILE
generate a model for the input formula, into the file model.out
.TP
\-S PATTERN, \--statistics=PATTERN
print statistics during of after the execution.
A valide pattern is of the form:

METRICS:INTERVAL:METRICS

The `:INTERVAL:METRICS` argument is optional
and declares metrics that will be printed at
regular intervals (e.g. `:100:r' shows the
number of rules applied so far, every 100
iterations of the algorithm).
.br
METRICS is made of one or more of the following
values:

c : number of closed branches

r : number of rules applied

The default is ':0:c'

.SH FILES
.I ~/.htabrc
configuration file
.SH EXAMPLES
.TP
Run HTab without semantic branching nor full clash, and write the tableaux states into out.tex:
.B htab
\-b 0 \-c 0 \-l out.tex \-f formula.frm
.PP
.TP
Run HTab in quiet mode:
.B htab
\-q \-f formula.frm
.PP
.SH INPUT FILE SYNTAX
The grammar for the files accepted by the prover is specified below. Comments
of the form '{' ALPHANUMERIC '}' are accepted anywhere in the file.

FILE := 'begin' FORMULAS 'end'
.br
FORMULAS := FORMULA | FORMULA ';' FORMULAS
.br
FORMULA := 
.br
  'true' | 'false' | 
.br
  PROPOSITION | NOMINAL |
.br
  NEGATION | CONJUNCTION | DISJUNCTION | IMPLICATION | DIMPLICATION | 
.br
  BOX | DIAMOND | AT | UBOX | UDIA |
.br
  '(' FORMULA ')'
.br
PROPOSITION  := 'P' NUMBER | 'p' NUMBER 
.br
NOMINAL      := 'N' NUMBER | 'n' NUMBER 
.br
RELATION     := 'R' NUMBER | 'r' NUMBER 
.br
NEGATION     := '!' FORMULA | '-' FORMULA | '~' FORMULA 
.br
CONJUNCTION  := FORMULA '&' FORMULA | FORMULA '^' FORMULA 
.br
DISJUNCTION  := FORMULA '|' FORMULA | FORMULA 'v' FORMULA 
.br
IMPLICATION  := FORMULA '->' FORMULA 
.br 
DIMPLICATION := FORMULA '<->' FORMULA 
.br
BOX          := '[]' FORMULA | 'box' FORMULA | '[' RELATION ']' FORMULA 
.br
DIAMOND      := '<>' FORMULA | 'dia' FORMULA | '<' RELATION '>' FORMULA 
.br
AT           := NOMINAL ':' FORMULA | '@' NOMINAL FORMULA 
.br
UBOX         := 'A' FORMULA
.br
UDIA         := 'E' FORMULA

See also the example formulas in 
.I /usr/share/doc/htab/examples
or
.I /usr/local/share/doc/htab/examples
.

.SH .htabrc SYNTAX
The .htabrc file must contain arguments as given to the HTab executable.
.SH AUTHOR
Guillaume Hoffmann (guillaume.hoffmann (at) loria.fr)
.SH AVAILABILITY
.TP
Home page
http://hylo.loria.fr/intohylo/htab.php
.TP
Code repository
http://trac.loria.fr/projects/htab
