Name:                HTab
Version:             1.5.4
Homepage:            http://code.google.com/p/intohylo/
Description:         Tableau based theorem prover for hybrid logics
License:             GPL
License-file:        COPYING
Author:              Guillaume Hoffmann, Carlos Areces, Daniel Gorín, Juan Heguiabehere
Maintainer:          guillaume.hoffmann@loria.fr
Cabal-version:       >= 1.2
Build-type:          Simple

Flag static
  Description: Build a static binary
  Default:     True

Executable          htab
  Main-is:             htab.hs
  Build-Depends:       base >= 4, base < 5,
                       mtl >= 1, mtl < 2,
                       containers < 1,
                       filepath > 1, filepath <= 2,
                       directory > 1, directory <= 2,
                       parallel,
                       hylolib == 1.3
  Hs-Source-Dirs:      src
  ghc-options:         -O2 -Wall -fglasgow-exts
  ghc-prof-options:    -auto-all

  if flag(static)
    ghc-options: -static -optl-static -optl-pthread
