Name:                HTab
Version:             1.2.1
Homepage:            http://hylo.loria.fr/intohylo/htab.php
Description:         Tableau based theorem prover for hybrid logics
License:             GPL
License-file:        COPYING
Author:              Guillaume Hoffmann, Carlos Areces, Daniel Gorín, Juan Heguiabehere
Maintainer:          guillaume.hoffmann@loria.fr
Build-Depends:       base, haskell98, mtl, filepath, hylolib

Executable:          htab
Main-is:             Htab.hs
other-modules:       HyLoLexer
		     HyLoParse
Hs-Source-Dirs:      src
Extra-source-files:  INSTALL man/htab.1.in man/htab.1 man/htab.1.html
ghc-options:         -Wall -fglasgow-exts
ghc-prof-options:    -auto-all
